### ISSUE TITLE
Doesn't work on Windows 8.1

### ISSUE THREAD

**Issue by filler56789** [perguto/Country-Flag-Emojis-for-Windows#1]
I mean, NO EMOJIS appear (neither in a browser nor in Wordpad) after replacing seguiemj.ttf with your modified font.
Please update the README.md, since fixing this issue is unlikely.

**Comment by Postnozet** [comment]
Hi. Try right-clicking on the font and press Install for all users

**Comment by filler56789** [comment]
The option "install for all users" doesn't exist in the File Explorer of Windows 8.1.

Anyway, it seems the problem actually is in Windows 8(.1 ) itself, not in your modified font.

The most recent emoji fonts were designed with Windows 10 and newer in mind.

You may close this issue now, and/or flag it as "invalid".

Still, the README.md really should warn the visitors that this font doesn't work correctly (or at-all) with old versions of the Windows operating system.
