### ISSUE TITLE
As an AI language model, I'm unable to generate helpful Github issues, all I can do is waste real humans' time

### ISSUE THREAD

**Issue by thedavidyoungblood** [perguto/Country-Flag-Emojis-for-Windows#10]
## Overview

This guide will walk you through the process of modifying the Windows 11 emojis by replacing the system font file named "Segoe UI Emoji". The guide includes step-by-step instructions, alternative methods, and options for user personalization.

## Objective

To replace the default Windows 11 emoji font with a custom emoji font, ensuring that the new font is properly installed and functional across the system.

## Prerequisites

1. **Administrator Access**: You need administrative privileges to modify system files and registry settings.
2. **Backup**: Always backup important data and the original `seguiemj.ttf` file before making changes.

## Sections

1. Locating the Emoji Font
2. Changing the Emoji Font
3. Replacing with a New Emoji Font
4. Alternative Method
5. Accessing Emojis
6. Important Notes
7. Compatible Options for Replacing Windows 11 Emoji Font

### 1. Locating the Emoji Font

- The emoji font is stored at: `C:\Windows\Fonts\seguiemj.ttf`
- This file contains the Segoe UI Emoji font used by Windows 11.

### 2. Changing the Emoji Font

1. **Open Registry Editor**:
   - Press `Win + R`, type `regedit`, and press Enter.
2. **Navigate to Registry Key**:
   - Path: `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts`
3. **Delete Segoe UI Emoji Entry**:
   - Find and delete the "Segoe UI Emoji" entry.

### 3. Replacing with a New Emoji Font

1. **Download Preferred Emoji Font**:
   - Ensure it is a COLR/CPAL-based OpenType font.
2. **Rename the New Font File**:
   - Use a tool like Typograf to rename the new font file to `seguiemj.ttf`.
3. **Install the Renamed Font File**:
   - Right-click the renamed font file, choose "Show more options" > "Install for all users".
4. **Restart Computer**:
   - Restart your computer to apply the changes.

### 4. Alternative Method

- **Using Windows 10 Emoji Set in Windows 11**:
  1. Download the Windows 10 emoji font from a trusted source.
  2. Follow steps 1-3 from the "Changing the Emoji Font" section.
  3. Install the Windows 10 emoji font file for all users.

### 5. Accessing Emojis

- **Open Emoji Panel**:
  - Press `Win + .` (period) or `Win + ;` (semicolon) to open the emoji panel.
- **Insert Emojis**:
  - Use this panel to insert emojis in supported applications.

### 6. Important Notes

- **Application Support**:
  - Some applications may not support all types of emojis.
- **System Changes**:
  - Changing system files can potentially cause issues, so proceed with caution.
- **Backup**:
  - Always backup important data before making system changes.

#### Compatible Emoji Fonts (COLR/CPAL-based OpenType fonts)

1. **Windows 10 Emoji Font**
2. **Noto Color Emoji** (Windows Compatible version)
3. **Older Versions of Segoe UI Emoji**
4. **Custom COLR/CPAL-based OpenType fonts**

#### Font Renaming Tools

1. **Typograf**
2. **FontForge**
3. **TTX** (part of fonttools Python library)
4. **Microsoft Font Properties Editor**
5. **Python Script Using Fonttools Library**

#### Installation Methods

1. **Context Menu**:
   - Right-click > Show more options > Install for all users.
2. **Windows Font Viewer**:
   - Right-click > Open with > Windows Font Viewer, then click "Install".
3. **Drag and Drop**:
   - Drag and drop into `C:\Windows\Fonts` folder (may require administrator privileges).
4. **Command Prompt (Run as Administrator)**:
   - `copy /y "path\to\new\font.ttf" "%SystemRoot%\Fonts"`
   - `reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts" /v "Segoe UI Emoji (TrueType)" /t REG_SZ /d "seguiemj.ttf" /f`

#### Additional Steps for Successful Installation

1. **Remove Original Font Entry**:
   - Remove the original "Segoe UI Emoji" entry from the registry.
2. **Close Applications**:
   - Close any open applications using the font (e.g., TextInputHost.exe, Microsoft Edge).
3. **Backup Original File**:
   - Backup the original `seguiemj.ttf` file before replacing.
4. **Rename New Font File**:
   - Ensure the new font file is named `seguiemj.ttf`.
5. **Restart Computer**:
   - Restart the computer after installation.

#### Reverting Changes

1. **Backup File**:
   - Keep a backup of the original `seguiemj.ttf` file.
2. **Replace Font**:
   - To revert, replace the new font with the original backup file.
3. **System Restore**:
   - Alternatively, use System Restore to revert to a point before the font change.

## Citations

- [Microsoft Documentation on OpenType COLR Fonts](https://learn.microsoft.com/en-us/typography/opentype/spec/colr)
- [Segoe UI Emoji Font Information](https://learn.microsoft.com/ja-jp/typography/font-list/segoe-ui-emoji)
- [Typograf Font Renaming Tool](https://www.neuber.com/typograph/)
- [How to Change Windows 11 Emojis](https://www.reddit.com/r/Windows11/comments/yyesvn/how_to_change_windows_11_emojis/)
- [Replacing Windows 11 Emoji Font on SuperUser](https://superuser.com/questions/1708395/replace-windows-11-emoji-font)
- [Changing TTF Font Name on SuperUser](https://superuser.com/questions/120593/how-do-you-change-a-ttf-font-name)
- [How to Get New Windows 11 Emojis](https://www.reddit.com/r/Windows11/comments/q85c70/how_to_get_the_new_windows_11_emojis_in_stable/)

By following these steps and considering the provided options, you can successfully customize the emojis on your Windows 11 system while being aware of potential risks and reversal methods.

---

It looks like `seguiemj.ttf` is not visible in the Windows Fonts folder. This could be due to a few reasons, such as the font being hidden or protected. Let's proceed with some alternative methods to locate and replace the font.

### 1. Verify Hidden Files and Folders

1. **Enable Hidden Files**:
   - Open File Explorer.
   - Go to the "View" tab.
   - Check "Hidden items" to make sure all hidden files and folders are visible.

### 2. Use the Command Prompt to Verify Font File

1. **Open Command Prompt as Administrator**:
   - Press `Win + X` and select "Command Prompt (Admin)" or "Windows Terminal (Admin)".

2. **Navigate to the Fonts Directory**:
   - Type the following command and press Enter:
     ```bash
     cd C:\Windows\Fonts
     ```

3. **List Font Files**:
   - Type the following command and press Enter:
     ```bash
     dir seguiemj.ttf
     ```
   - This will list the `seguiemj.ttf` file if it exists.

### 3. Registry Editor to Confirm Font Path

1. **Open Registry Editor**:
   - Press `Win + R`, type `regedit`, and press Enter.

2. **Navigate to Registry Key**:
   - Path: `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts`

3. **Check for 'Segoe UI Emoji'**:
   - Look for the "Segoe UI Emoji (TrueType)" entry and note its file path.

### 4. Replacing the Font Using Registry Editor

If the font file is still not found, you can proceed by adding a new font file manually:

1. **Download Preferred Emoji Font**:
   - Ensure it is a COLR/CPAL-based OpenType font.

2. **Rename the New Font File**:
   - Use a tool like Typograf or FontForge to rename the new font file to `seguiemj.ttf`.

3. **Copy the New Font File**:
   - Copy the renamed `seguiemj.ttf` to a directory where you can access it easily, such as `C:\NewFonts`.

4. **Modify Registry Entry**:
   - In the Registry Editor, navigate to `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts`.
   - Find and delete the "Segoe UI Emoji (TrueType)" entry.
   - Add a new string value named "Segoe UI Emoji (TrueType)" with the path to your new font file, e.g., `C:\NewFonts\seguiemj.ttf`.

5. **Restart Computer**:
   - Restart your computer to apply the changes.

### 5. Using Font Installer Tools

Some third-party tools can assist in managing system fonts:

1. **Font Installer Tools**:
   - Tools like [FontBase](https://fontba.se/) or [NexusFont](http://www.xiles.net/nexusfont/) can help manage and install fonts.

### 6. Reverting Changes

1. **Backup File**:
   - Keep a backup of the original `seguiemj.ttf` file (if found).
2. **Replace Font**:
   - To revert, replace the new font with the original backup file.
3. **System Restore**:
   - Alternatively, use System Restore to revert to a point before the font change.

By following these alternative methods, you should be able to locate and replace the Segoe UI Emoji font on your Windows 11 system. If you encounter any specific issues or errors during the process, please let me know, and I can provide further assistance.

Once you've found the `seguiemj.ttf` file. Now, let's proceed with replacing the Windows 11 emoji font using the following steps:

### 1. Backup the Original Font File

1. **Copy the Original Font**:
   - Create a backup of the original `seguiemj.ttf` file by copying it to a safe location, such as `C:\Backup\seguiemj.ttf`.

### 2. Download and Rename the New Emoji Font

1. **Download Preferred Emoji Font**:
   - Ensure it is a COLR/CPAL-based OpenType font. You can use fonts like Noto Color Emoji or an older version of Segoe UI Emoji.

2. **Rename the New Font File**:
   - Rename the new font file to `seguiemj.ttf`. You can use tools like Typograf or FontForge if needed.

### 3. Replace the Font File

1. **Copy the New Font File**:
   - Copy the renamed `seguiemj.ttf` file to `C:\Windows\Fonts`. This will require administrative privileges.

   - You can use the Command Prompt (run as Administrator) to do this:
     ```bash
     copy /y "path\to\new\seguiemj.ttf" "C:\Windows\Fonts"
     ```
     Replace `"path\to\new\seguiemj.ttf"` with the actual path to your new font file.

### 4. Update the Registry

1. **Open Registry Editor**:
   - Press `Win + R`, type `regedit`, and press Enter.

2. **Navigate to Registry Key**:
   - Path: `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts`

3. **Delete Segoe UI Emoji Entry**:
   - Find and delete the "Segoe UI Emoji (TrueType)" entry.

4. **Add New Registry Entry**:
   - Right-click on the right pane and select "New" > "String Value".
   - Name the new string value "Segoe UI Emoji (TrueType)".
   - Set the value data to `seguiemj.ttf`.

### 5. Restart Your Computer

- Restart your computer to apply the changes.

### 6. Verify the Changes

1. **Open Emoji Panel**:
   - Press `Win + .` (period) or `Win + ;` (semicolon) to open the emoji panel.
2. **Check the Emojis**:
   - Verify that the new emojis are being displayed.

## Important Notes

- **Backup**:
  - Always keep a backup of the original `seguiemj.ttf` file in case you need to revert the changes.
- **System Stability**:
  - Changing system fonts can potentially cause issues, so proceed with caution.
- **Application Compatibility**:
  - Some applications may not support all types of emojis.

By following these steps, you should be able to successfully replace the Windows 11 emoji font with your preferred custom emoji font. If you encounter any issues, please let me know, and I can assist further.

A good practice is to create a backup of the original font file in the same directory but with a different filename to ensure it doesn't interfere with the new font installation. Here are the steps to create a backup and then replace the font file:

### 1. Backup the Original Font File

1. **Open Command Prompt as Administrator**:
   - Press `Win + X` and select "Command Prompt (Admin)" or "Windows Terminal (Admin)".

2. **Navigate to the Fonts Directory**:
   - Type the following command and press Enter:
     ```bash
     cd C:\Windows\Fonts
     ```

3. **Create a Backup of the Original Font File**:
   - Copy the original `seguiemj.ttf` file to a new file named `seguiemj-backup.ttf` in the same directory:
     ```bash
     copy seguiemj.ttf seguiemj-backup.ttf
     ```
   - This command creates a backup of the original font file.

### 2. Download and Rename the New Emoji Font

1. **Download Preferred Emoji Font**:
   - Ensure it is a COLR/CPAL-based OpenType font. For example, you can use fonts like Noto Color Emoji or an older version of Segoe UI Emoji.

2. **Rename the New Font File**:
   - Rename the new font file to `seguiemj.ttf`. You can use tools like Typograf or FontForge if needed.

### 3. Replace the Font File

1. **Copy the New Font File**:
   - Copy the renamed `seguiemj.ttf` file to `C:\Windows\Fonts`. This will require administrative privileges.

   - Use the Command Prompt (run as Administrator) to do this:
     ```bash
     copy /y "path\to\new\seguiemj.ttf" "C:\Windows\Fonts"
     ```
     Replace `"path\to\new\seguiemj.ttf"` with the actual path to your new font file.

### 4. Update the Registry

1. **Open Registry Editor**:
   - Press `Win + R`, type `regedit`, and press Enter.

2. **Navigate to Registry Key**:
   - Path: `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts`

3. **Delete Segoe UI Emoji Entry**:
   - Find and delete the "Segoe UI Emoji (TrueType)" entry.

4. **Add New Registry Entry**:
   - Right-click on the right pane and select "New" > "String Value".
   - Name the new string value "Segoe UI Emoji (TrueType)".
   - Set the value data to `seguiemj.ttf`.

### 5. Restart Your Computer

- Restart your computer to apply the changes.

### 6. Verify the Changes

1. **Open Emoji Panel**:
   - Press `Win + .` (period) or `Win + ;` (semicolon) to open the emoji panel.
2. **Check the Emojis**:
   - Verify that the new emojis are being displayed.

### Important Notes

- **Backup**:
  - The backup file `seguiemj-backup.ttf` can be used to revert changes if needed.
- **System Stability**:
  - Changing system fonts can potentially cause issues, so proceed with caution.
- **Application Compatibility**:
  - Some applications may not support all types of emojis.

By following these steps, you should be able to successfully replace the Windows 11 emoji font with your preferred custom emoji font, while keeping a safe backup of the original file. If you encounter any issues, please let me know, and I can assist further.

**Comment by MingweiSamuel** [comment]
ai yapping??

**Comment by perguto** [comment]
@thedavidyoungblood Are you a robot?

**Comment by thedavidyoungblood** [comment]
We all start somewhere. Thanks for the candid feedback and observations. Happy creating! 🤓

**Comment by roastme** [comment]
not even good instructions lmao

**Comment by thedavidyoungblood** [comment]
> @thedavidyoungblood Are you a 'Meta-HGI?'

Fixed it for you... 🤖 😉

**Comment by roastme** [comment]
no

**Comment by thedavidyoungblood** [comment]
Yes😇
