### ISSUE TITLE
Very sharp

### ISSUE THREAD

**Issue by Postnozet** [perguto/Country-Flag-Emojis-for-Windows#2]
Everything is perfect, works even in Chrome. But the emoji looks very sharp, can this be fixed?

**Comment by perguto** [comment]
Unfortunately, I don't think so as Microsoft uses a different file format for colored emojis than Google, and this format seems to lack Google's better anti-aliasing.

However, you can install the Tampermonkey Chrome extension and my Tampermonkey script: https://perguto.github.io/tampermonkey/Country%20Emojis.user.js

This will give you the properly anti-aliased country flags in your browser
